name: real_estate_app
description: MVVM Flutter app (Splash + SignIn) with Firebase Auth

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.2
  go_router: ^16.2.0
  stacked: ^3.5.0
  stacked_services: ^1.6.0

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
