// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgWZJRMISD4GT9bBZd3LsBFZkEcSSm31s',
    appId: '1:248410777428:web:b5070d47d5da454bc1cac1',
    messagingSenderId: '248410777428',
    projectId: 'realestateapp-b535b',
    authDomain: 'realestateapp-b535b.firebaseapp.com',
    storageBucket: 'realestateapp-b535b.firebasestorage.app',
    measurementId: 'G-BFCSWHL0JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtH2A2EMtWzCc451bu0QeHWEXPaNEnfk',
    appId: '1:248410777428:android:13c117242a5e0168c1cac1',
    messagingSenderId: '248410777428',
    projectId: 'realestateapp-b535b',
    storageBucket: 'realestateapp-b535b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD4yprPjyEpeEYNSBF-DVNh4lhV_OMdvE',
    appId: '1:248410777428:ios:fe2438d17add61a6c1cac1',
    messagingSenderId: '248410777428',
    projectId: 'realestateapp-b535b',
    storageBucket: 'realestateapp-b535b.firebasestorage.app',
    iosBundleId: 'com.example.statemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD4yprPjyEpeEYNSBF-DVNh4lhV_OMdvE',
    appId: '1:248410777428:ios:fe2438d17add61a6c1cac1',
    messagingSenderId: '248410777428',
    projectId: 'realestateapp-b535b',
    storageBucket: 'realestateapp-b535b.firebasestorage.app',
    iosBundleId: 'com.example.statemanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgWZJRMISD4GT9bBZd3LsBFZkEcSSm31s',
    appId: '1:248410777428:web:5fff80d3ef533f2dc1cac1',
    messagingSenderId: '248410777428',
    projectId: 'realestateapp-b535b',
    authDomain: 'realestateapp-b535b.firebaseapp.com',
    storageBucket: 'realestateapp-b535b.firebasestorage.app',
    measurementId: 'G-L5SPY0WL9R',
  );
}
